# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [2]:
import numpy
from keras.datasets import cifar100, cifar10
import numpy as np
np.random.seed(100)

# 資料準備

In [6]:
(x_train, y_train), (x_test, y_test) = cifar100.load_data()
(x_train_10, y_train_10), (x_test_10, y_test_10) = cifar10.load_data()

In [7]:
# 看一下資料
# 知資料本質上沒差異
def show_size(data, *argv):
    print(f'len: {len(data)}')
    print(f'shape: {data.shape}')
    print()
    for arg in argv:
        print(f'len: {len(arg)}')
        print(f'shape: {arg.shape}')
        print('='*20)

show_size(x_train, y_train, x_test, y_test, x_train_10, y_train_10, x_test_10, y_test_10)

len: 50000
shape: (50000, 32, 32, 3)

len: 50000
shape: (50000, 1)
len: 10000
shape: (10000, 32, 32, 3)
len: 10000
shape: (10000, 1)
len: 50000
shape: (50000, 32, 32, 3)
len: 50000
shape: (50000, 1)
len: 10000
shape: (10000, 32, 32, 3)
len: 10000
shape: (10000, 1)


# Image normalize 

In [8]:
x_train_normalize = x_train.astype('float32') / 255.0
x_test_normalize = x_test.astype('float32') / 255.0
x_train_10_normalize = x_train_10.astype('float32') / 255.0
x_test_10_normalize = x_test_10.astype('float32') / 255.0

In [9]:
print(x_train_normalize[0][0][0])

[1. 1. 1.]


# 轉換label 為OneHot Encoding

In [10]:
print(y_train.shape)

(50000, 1)


In [11]:
from keras.utils import np_utils
y_train_onehot = np_utils.to_categorical(y_train)
y_test_onehot = np_utils.to_categorical(y_test)

y_train_10_onehot = np_utils.to_categorical(y_train_10)
y_test_10_onehot = np_utils.to_categorical(y_test_10)

In [13]:
# 差別在這
print(y_train_onehot.shape)
print(y_train_10_onehot.shape)

(50000, 100)
(50000, 10)


In [16]:
y_train_onehot[:2]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [17]:
y_train_10_onehot[:2]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)